### PR TITLE
WTL9.0 upgrade and WinAmp compiler warning fix

### PR DESCRIPTION
**Pull request by gdwnldsKSC**
This includes the necessary fix to enable building with WTL9.0, and also removes some legacy code from WinAmp plugin to remove a compiler warning due to '.' characters in the #ifdef 

Brings us to nominal compatibility with VS 2008 to VS 2013 with WTL 9.0. 

This can close open issue #5 for WTL9 porting.

### CODE REVIEW

**Comment by gdwnldsKSC** [comment]
NOTE: Neither change breaks Hydra with building with WTL 8.1 - The change is backwards compatible.

**Comment by gdwnldsKSC** [comment]
@hydra Requesting review.

Changed DNS resolver to newer (XP and up only) API (GetAddrInfo instead of GetHostByName) while maintaining existing code compatiblity - now just simple as setting a flag to enable IPv6 resolution (once other code is updated to support IPv6 addresses)

Fixed WinAmp compiler warning

Upgraded LibXML to 2.7.8

WTL 9.0 support/upgrade

Documentation updates. 

Removing gethostbyname calls paves the way for IPv6 support, and as noted in my first comment, WTL9 issue can now be closed with these changes.

**Comment by gdwnldsKSC** [comment]
Also fixed broken sys_printf calls, due to case sensitivity (only 4 calls were broken that i've found so far) - because of the define it needs to be sys_Printf with the capital P

**Comment by gdwnldsKSC** [comment]
@hydra  Question, do you prefer changes in small batches, or in larger chunks? I'm trying to limit the size of what I submit to each iteration of progress, but not sure how you'd prefer if there's a backlog of changes I would like to submit

**Comment by hydra** [comment]
@gdwnldsKSC I much prefer small focused atomic changes. With can comprise of one or more atomic commits.   Smaller PRs are easier to review and stand a much greater chance of being reviewed and merged in a timely manner.

**Comment by gdwnldsKSC** [comment]
@hydra  understood, i'm still learning git (it's a way different mindset than CVS and SVN) so just recently merged all my branches with tags, from what i can see i can use tags to send PRs in defined small ways. I haven't merged my dev into my master yet because that's a lot more stuff, but have like 4 tags that are progress periods. 

Should I resync to your repo then apply changes selectively with tags and submit them as separate PRs?

**Comment by gdwnldsKSC** [comment]
FWIW, also, libxml will /always/ have a ton of compiler warnings until we get to VS 2015 or later.

**Comment by hydra** [comment]
> FWIW, also, libxml will /always/ have a ton of compiler warnings until we get to VS 2015 or later.

yeah, in 3rd party libraries is less of an issue.  additional build step could could be used to compile the library such that it doesn't complain and then have the resulting library linked with the main code.  that would keep the noise down and can then be later addressed as-required as a separate task.  ideally there should be no warnings from any of the main code though.

**Comment by hydra** [comment]
> from what i can see i can use tags to send PRs in defined small ways. I haven't merged my dev into my master yet because that's a lot more stuff, but have like 4 tags that are progress periods.

you don't usually use tags to create PR, the process is:
1) fork a repo.
2) make a branch on your machine from the `master` branch on your repo
3) make changes on that branch.
4) push those changes to your fork.
5) create a PR from that branch on your repo to the official repo.

then later, when you want to make a new PR:

6) update your `master`  branch on your repo from the `master` branch on the official repo.
7) continue from step 2.

But again, there's lots of documentation on github.com and on various blogs and videos on how do to all this.

> Should I resync to your repo then apply changes selectively with tags and submit them as separate PRs?

yes, as per the above process.

if you already have changes then you can 'rebase' your PR branches on a branch that has the latest commit from the official repo.

e.g.

```
git fetch upstream
git checkout master
git merge upstream/master --ff-only
git checkout my-branch
git rebase master
git push origin my-branch
```

if you don't have a remote called `upstream` then add a new 'remote' that points to the official repo first.

but again, see other tutorials etc for more information on git usage/flow.

**Pull request closed without merging**
